name: CI

on:
  push:
    branches-ignore: [ staging.tmp ]
  pull_request:
    branches-ignore: [ staging.tmp ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
    steps:
    - uses: actions/checkout@v2
    - run: cargo check --all-features
    - run: cargo test --no-run

  wasm:
    runs-on: [ubuntu-18.04]
    env:
      RUSTFLAGS: --cfg=web_sys_unstable_apis
    steps:
    - uses: actions/checkout@v2
    - run: rustup target add wasm32-unknown-unknown
    - name: Check WebGPU
      run: cargo check --all-targets --target=wasm32-unknown-unknown
    - name: Check WebGL
      run: cargo check --all-targets --target=wasm32-unknown-unknown --features webgl

  docs:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
      continue-on-error: true
    - name: cargo doc
      run: cargo --version; cargo doc --lib --no-deps
      continue-on-error: true
